version: '3'
services:
  cairis-mysql:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: my-secret-pw

  cairis:
    build:
      context: ./cairis
    depends_on:
      - cairis-mysql
    ports: 
      - 80:8000